services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: orderbot
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports: ["5433:5432"] # avoid conflicts with local postgres
    volumes: ["pgdata:/var/lib/postgresql/data"]

  redis:
    image: redis:7
    ports: ["6379:6379"]

volumes:
  pgdata: {}
